version: '3.4'

services:
  samba:
    image: localhost/robby-samba
    environment:
      - TZ=America/Los_Angeles
      - SHARE=/mnt/share
      - READ_ONLY=no
      - GUEST=yes
      - GROUP=rox
      - CREATE_MASK=0770
    ports:
      - 134:134/udp
      - 138:138/udp
      - 139:139
      - 445:445
    volumes:
      -/home/robby/Personal/Development/test_smb:/mnt/share:Z